### ISSUE TITLE
tests fails under ruby3.0

### ISSUE THREAD

**Issue by terceiro** [moneta-rb/moneta#203]
Hi,

When running the test suite on ruby3.0, the tests fail (while they pass on ruby2.7). This looks related to
[Separation of positional and keyword arguments in Ruby 3.0](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/).

```
$ ruby2.7 -S rspec spec/moneta/stack_file_memory_spec.rb 
Run options: exclude {:unsupported=>true, :broken=>true}
...............................................................

Finished in 1.93 seconds (files took 0.10449 seconds to load)
63 examples, 0 failures

$ ruby3.0 -S rspec spec/moneta/stack_file_memory_spec.rb 
Run options: exclude {:unsupported=>true, :broken=>true}
........FFFFFFFFFFFFFFFFFFFFFFFFFF.FFFFF.FFF.FFF.FFF.FFF.FFF...

Failures:

  1) stack_file_memory null feature reads from keys like a Hash
     Failure/Error:
       moneta_property_of(keys: 1).check do |keys:|
         store[keys[0]].should be_nil
         store.load(keys[0]).should be_nil
       end
     
     ArgumentError:
       0 successful tests, failed on:
       {:keys=>["MIaDBcsYek/uUmgGM/tYHOhB"]}
     
       missing keyword: :keys
     Shared Example Group: :null called from ./spec/helper.rb:283
     # ./spec/features/null.rb:3:in `block (3 levels) in <top (required)>'
     # /usr/share/rubygems-integration/all/gems/rantly-2.0.0/lib/rantly/property.rb:33:in `block in check'
     # /usr/share/rubygems-integration/all/gems/rantly-2.0.0/lib/rantly/generator.rb:81:in `generate'
     # /usr/share/rubygems-integration/all/gems/rantly-2.0.0/lib/rantly/property.rb:31:in `check'
     # ./spec/features/null.rb:3:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # ArgumentError:
     #   missing keyword: :keys
     #   ./spec/features/null.rb:3:in `block (3 levels) in <top (required)>'

[...]
Finished in 0.06783 seconds (files took 0.11136 seconds to load)
63 examples, 46 failures
[...]
```

**Comment by asppsa** [comment]
Hi,  yes you are correct.  We have an existing issue to convert the moneta API from option hashes to keyword args here: #175

**Comment by asppsa** [comment]
As you mentioned in #175, there are really two issues here - the tests themselves and the code, both have 3.0 issues.  Let's keep this ticket focused on the former.

**Comment by asppsa** [comment]
@terceiro most tests are now passing on ruby 3, but there are some adapters/proxies that are failing.  I think this ticket can be closed however, as the issue is now with those adapters & prroxies rather than the tests.
