### ISSUE TITLE
store_large unit test always failing on s390x

### ISSUE THREAD

**Issue by jcharaoui** [moneta-rb/moneta#262]
When running the test suite in the `ruby-moneta` Debian package, this test always fails on the **s390x** architecture:

```
 94s   1) adapter_client store_large feature should store values up to 32k
 94s      Failure/Error: store['large'].should == value
 94s 
 94s      EOFError:
 94s        Server closed socket
 94s      Shared Example Group: :store_large called from ./spec/helper.rb:273
 94s      # ./spec/features/store_large.rb:5:in `block (2 levels) in <top (required)>'
 94s      # /usr/share/rubygems-integration/all/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
 94s      # /usr/share/rubygems-integration/all/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
 94s      # /usr/share/rubygems-integration/all/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
 94s      # /usr/share/rubygems-integration/all/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
 94s      # /usr/share/rubygems-integration/all/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'
```

Full test log: https://ci.debian.net/packages/r/ruby-moneta/testing/s390x/44820547/

I understand tracking this down might not be straightforward if you don't have access to an IBM mainframe, but I'm opening this ticket in case you might figure out an obvious cause for this.

**Comment by utkarsh2102** [comment]
Hey, this is not just s390x anymore but I think this is also failing on other architectures randomly. Given this project is not really maintained anymore, I'm going to disable this test for now. But someone needs to look into this in detail. :(

**Comment by asppsa** [comment]
Is it some specific Ruby version that this happens with?
